# Generated by Django 6.1 on 2026-08-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='منتشر شده')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='نامک')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('summary', models.TextField(blank=True, max_length=500, null=True, verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='متن اصلی')),
                ('event_type', models.CharField(choices=[('news', 'اخبار'), ('event', 'رویداد حضوری'), ('webinar', 'وبینار'), ('call', 'فراخوان عمومی')], db_index=True, default='news', max_length=20, verbose_name='نوع')),
                ('event_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ برگزاری')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/', verbose_name='تصویر شاخص')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
            ],
            options={
                'verbose_name': 'رویداد / خبر',
                'verbose_name_plural': 'رویدادها و اخبار',
                'ordering': ['-published_at', '-event_date'],
                'indexes': [models.Index(fields=['event_type', 'is_published', 'event_date'], name='events_even_event_t_eb1b8f_idx')],
            },
        ),
    ]
