# Generated by Django 6.1 on 2026-08-31 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='منتشر شده')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='نامک')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('summary', models.TextField(blank=True, max_length=500, null=True, verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='متن کامل فراخوان')),
                ('call_type', models.CharField(choices=[('research', 'فراخوان مقاله'), ('grant', 'فراخوان گرنت'), ('job', 'فراخوان استخدام'), ('other', 'سایر')], db_index=True, default='research', max_length=20, verbose_name='نوع فراخوان')),
                ('deadline', models.DateTimeField(db_index=True, verbose_name='مهلت ارسال')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل تماس')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن تماس')),
                ('document', models.FileField(blank=True, null=True, upload_to='events/calls/documents/', verbose_name='فایل پیوست')),
            ],
            options={
                'verbose_name': 'فراخوان',
                'verbose_name_plural': 'فراخوان\u200cها',
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='منتشر شده')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='نامک')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('summary', models.TextField(blank=True, max_length=500, null=True, verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='متن کامل')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/news/covers/', verbose_name='تصویر شاخص')),
                ('source', models.URLField(blank=True, max_length=255, null=True, verbose_name='منبع')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'ordering': ['-published_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name': 'رویداد', 'verbose_name_plural': 'رویدادها'},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_event_t_eb1b8f_idx',
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ظرفیت'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 8, 31, 10, 10, 14, 730265, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مکان'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مهلت ثبت\u200cنام'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 8, 31, 10, 10, 21, 883683, tzinfo=datetime.timezone.utc), verbose_name='تاریخ شروع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(verbose_name='توضیحات کامل'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/events/covers/', verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('in_person', 'حضوری'), ('online', 'آنلاین'), ('hybrid', 'ترکیبی (حضوری و آنلاین)')], db_index=True, default='in_person', max_length=20, verbose_name='نوع برگزاری'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
    ]
