# Generated by Django 6.1 on 2026-09-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام حامی')),
                ('logo', models.ImageField(upload_to='site/supporters/', verbose_name='لوگو')),
                ('website_url', models.URLField(blank=True, verbose_name='لینک وبسایت')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'حامی',
                'verbose_name_plural': 'حامیان',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
