# Generated by Django 6.1 on 2026-09-04 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='کلید')),
                ('value', models.CharField(max_length=500, verbose_name='مقدار')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات مدیریت',
                'verbose_name_plural': 'تنظیمات مدیریت',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('bulk_delete', 'حذف گروهی'), ('publish', 'انتشار'), ('unpublish', 'عدم انتشار'), ('block', 'مسدودیت'), ('unblock', 'رفع مسدودیت'), ('promote', 'ارتقا سطح'), ('login', 'ورود'), ('logout', 'خروج'), ('download', 'دانلود')], db_index=True, max_length=20, verbose_name='عملیات')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='نام مدل')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='شناسه شیء')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='عنوان شیء')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='تغییرات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('user_agent', models.TextField(blank=True, verbose_name='مرورگر')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ فعالیت',
                'verbose_name_plural': 'لاگ\u200cهای فعالیت',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='managements_model_n_8a758a_idx'), models.Index(fields=['timestamp'], name='managements_timesta_0e0bf1_idx'), models.Index(fields=['user'], name='managements_user_id_5419da_idx')],
            },
        ),
    ]
