# Generated by Django 6.1 on 2026-09-01 09:12

import django.core.validators
import guides.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('file', models.FileField(upload_to='guides/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'zip']), guides.models.validate_guide_file_size], verbose_name='فایل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'راهنما',
                'verbose_name_plural': 'راهنماها',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
